services:
  web:
    build: .
    container_name: nonotes_website
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
